-- Secure server-only PIN verifier with rate limiting.
-- Safe to run after staff_pins and staff_roles already exist.

create table if not exists public.staff_pin_attempts (
  id bigint generated by default as identity primary key,
  client_key text not null,
  attempted_at timestamptz not null default now(),
  success boolean not null default false
);

alter table public.staff_pin_attempts enable row level security;
revoke all on table public.staff_pin_attempts from anon, authenticated;

create index if not exists staff_pin_attempts_client_time_idx
  on public.staff_pin_attempts (client_key, attempted_at desc);

create or replace function public.verify_staff_pin_server(
  p_pin text,
  p_client_key text
)
returns table (
  status text,
  user_email text,
  staff_role text
)
language plpgsql
security definer
set search_path = public, auth, extensions
as $$
declare
  v_email text;
  v_role text;
  v_failures integer;
begin
  -- Keep the attempts table small.
  delete from public.staff_pin_attempts
  where attempted_at < now() - interval '24 hours';

  select count(*)::integer
  into v_failures
  from public.staff_pin_attempts
  where client_key = p_client_key
    and success = false
    and attempted_at > now() - interval '15 minutes';

  if v_failures >= 5 then
    return query select 'locked'::text, null::text, null::text;
    return;
  end if;

  select u.email::text, sr.role::text
  into v_email, v_role
  from public.staff_pins sp
  join auth.users u on u.id = sp.user_id
  join public.staff_roles sr on sr.user_id = sp.user_id
  where sp.pin_hash = extensions.crypt(p_pin, sp.pin_hash)
  limit 1;

  if v_email is null then
    insert into public.staff_pin_attempts (client_key, success)
    values (p_client_key, false);
    return query select 'invalid'::text, null::text, null::text;
    return;
  end if;

  -- Successful login clears recent failed attempts from this client.
  delete from public.staff_pin_attempts
  where client_key = p_client_key and success = false;

  insert into public.staff_pin_attempts (client_key, success)
  values (p_client_key, true);

  return query select 'ok'::text, v_email, v_role;
end;
$$;

revoke all on function public.verify_staff_pin_server(text, text) from public;
revoke all on function public.verify_staff_pin_server(text, text) from anon;
revoke all on function public.verify_staff_pin_server(text, text) from authenticated;
grant execute on function public.verify_staff_pin_server(text, text) to service_role;
